package.json, src/components/root_layout.tsx, src/templates/qa_hpwh.mdx
- Changed the web app title to Quality Install Tool.
- Made one update to the qa_hpwh template per Edward's request.
=> 7 complete hpwh template

src/components/editor_flexbox.tsx, src/components/json_store_view.tsx, src/components/mdx_template_view.tsx, src/components/mdx_wrapper.tsx, src/components/photo.tsx, src/components/photo_input.tsx, src/components/photo_input_wrapper.tsx, src/components/photo_wrapper.tsx, src/components/store.tsx, src/templates/templates_config.ts, src/types/attachment.type.ts, src/utilities/photo_utils.tsx
No idea how to fix the rest. Anyone have suggestions?
=> Fixed all but store.tsx and photo related typescript error

src/App.css, src/App.tsx, src/components/home.tsx, src/components/jobs_view.tsx, src/components/store.tsx, src/components/string_input.tsx, src/components/text_input.tsx
I'm not sure how to store it but it is working.
=> jobs view done

.eslintrc.js, package.json, yarn-error.log, yarn.lock
-fix typescript errors
-makes comilation look clean
-fix linter rules config
=> Fixes linter config and typescript errors

src/components/home.tsx, src/templates/qa_hpwh.mdx, src/templates/templates_config.ts
Commit for
Knock out List 2
Knock out List 1 -  Issue 1 & 2
=> Fix for Knock out List

src/components/jobs_view.tsx, src/components/string_input_modal.tsx
Back button is functional on main locally...not sure why it is not on the page.
Please check if back button is also working on your laptop locally :/
=> fixed regex

src/components/mdx_wrapper.tsx, src/components/page_break.tsx
=> page break component

src/components/mdx_wrapper.tsx, src/templates/doe_workflow_hpwh.mdx, src/templates/reusable/project_info_inputs.mdx, src/templates/reusable/project_info_report.mdx
Changes for creating a reusable template for Project Information Input Date in all the reports
=> Reusable templates

README.md, public/index.html, src/components/jobs_view.tsx, src/components/mdx_wrapper.tsx, src/components/print_section wrapper.tsx, src/components/print_section.tsx, src/types/metadata.type.ts, src/utilities/database_utils.tsx
Some feedback from Edward Louie was that when working on multiple projects, it can be hard to organize reports since the tool prints everything to the same filename.
=> Pdf file name redo

src/templates/doe_workflow_attic_air_sealing.mdx, src/templates/doe_workflow_attic_insulation.mdx, src/templates/doe_workflow_hpwh.mdx
1. Replaced the text 'street' with 'building' as per Edward's request in Building Photo Description
2. Replaced TextInput to StringInput in Attic Air Sealing and Attic Insulation Templates
=> Template changes - text change and TextInput to StringInput update

src/components/store.tsx, src/utilities/photo_utils.tsx
Resolves: https://github.com/pnnl/Quality-Install-Tool/issues/123
Converts all dates to ISO string
tested by uploading photos and logging meta data and store as a whole. Validated that the dates were in the correct format in attachments and in the metadata
=> 123- standardizes datetime across the application store

public/print.css, src/App.css, src/components/string_input_modal.tsx
-Disables add button if input is invalid
-Stylizes the error message
-runs validation each keystroke
-autofocuses input
-Tested by entering valid and invalid inputs to verify functionality
=> 139: Improves project name modal

public/print.css, src/App.css, src/components/photo.tsx, src/components/photo_input.tsx, src/components/photo_input_wrapper.tsx, src/components/radio.tsx
=> Radio Label improvement and PhotoInput 'uploadable' option

public/print.css, src/App.css, src/components/number_input.tsx, src/components/number_input_wrapper.tsx, src/components/string_input.tsx, src/components/string_input_wrapper.tsx
Code changes for the following
1. Reverted the cursor changes in StringInput and NumberInput Component
2. Fix for #146 
3. Adding hint to the StringInput and NumberInput components
4. Added fix for #152 from #156 
Tested the changes in MacBook - safari and chrome, IOS (iPad)-  Safari and Chrome and Android (Samsung phone) - Chrome
=> Code fixes and reverting changes

src/App.css, src/components/jobs_view.tsx, src/components/string_input_modal.tsx, src/templates/doe_workflow_central_ducted_split_heat_pump.mdx, src/templates/doe_workflow_ductless_heat_pump.mdx
1) Addition to the heat pump workflows as per Edward's request
2) Fix for the project name validation in the modal dialog
=> 172 additions to the heat pump quality installation workflows

tsconfig.json, yarn.lock
Reverting the yarn.lock and tsconfig.json that was wrongly merged
=> Revert yarn lock 

src/components/workflow_view.tsx
Placed the disclaimer text in the Workflows/Installations view.
=> Disclaimer text above the workflow names

.github/workflows/release_merge_to_production.yml
- This workflow creates a pull request to merge changes from the main branch into the production branch once a release is published. 
- The pull request requires manual intervention to review and confirm the changes before merging into production. This process helps ensure that the release changes moving to production are verified, especially considering that multiple pull requests may have been merged into the main branch after testing.
**Please note** that this workflow has not been tested in this repository branch but has been tested in a personal repository.
Pull request will be created as below by github-action bot
=> Github workflow for release merge to production

src/components/mdx_wrapper.tsx, src/components/show_or_hide.tsx, src/templates/doe_workflow_central_ducted_split_heat_pump.mdx, src/templates/doe_workflow_ductless_heat_pump.mdx, src/templates/ira_doe_workflow_central_ducted_split_heat_pump.mdx, src/templates/ira_doe_workflow_ductless_heat_pump.mdx, src/templates/ira_doe_workflow_hpwh.mdx, src/templates/templates_config.ts
- New component added to show to hide its content based in the 'visible' option provided.
- Installation workflow name changed as per the request.
=> Component to Show or Hide the content 

package.json, src/components/db_details.tsx, src/components/root_layout.tsx, src/templates/templates_config.ts
Merged all workflow templates to be deployed as a single application.
=> Merging all workflows into one app

package.json, src/components/home.tsx, yarn.lock
react-tooltip is not present in pnnl artifacts so the build was failing in test.  I remove the usage, as it is not necessary. 
Will debug the issue later.
=> removed react-tooltip failing in the build

src/templates/doe_workflow_heat_pump_ducted.mdx, src/templates/doe_workflow_heat_pump_ductless.mdx, src/templates/ira_doe_workflow_high_efficiency_gas_furnace.mdx
Updated the display of Manual J content in the report section of the following templates
- Heat Pump Ducted
- Heat Pump Ductless
- High Efficiency Gas Furnace
=> Template updates to rearrange the Manual J display in report

src/templates/ira_doe_workflow_high_efficiency_gas_furnace.mdx, src/templates/ira_doe_workflow_high_efficiency_modulating_boiler.mdx, src/templates/ira_doe_workflow_high_efficiency_water_heater.mdx
**High Efficiency Gas Furnace**
**High Efficiency Water Heater**
**High Efficiency Modulating Boiler**
**High Efficiency Gas Furnace**
**High Efficiency Water Heater**
**High Efficiency Modulating Boiler**
=> 245 gas workflows template updates

src/templates/doe_workflow_heat_pump_ducted.mdx, src/templates/doe_workflow_heat_pump_ductless.mdx
=> 306-heat-pump-ductless-workflow-addition

package.json, src/__tests__/__mocks__/heic2any.ts, src/__tests__/components/labelValue.test.tsx, src/components/label_value.tsx, src/components/label_value_wrapper.tsx, src/templates/doe_workflow_combustion_appliance_safety_tests.mdx, src/templates/doe_workflow_heat_pump_ducted.mdx, src/templates/doe_workflow_heat_pump_ductless.mdx, src/templates/doe_workflow_heat_pump_water_heater.mdx, src/templates/index.ts, src/templates/ira_doe_workflow_attic_air_sealing_and_insulation.mdx, src/templates/ira_doe_workflow_duct_air_sealing_and_insulation.mdx, src/templates/ira_doe_workflow_floor_air_sealing_and_insulation.mdx, src/templates/ira_doe_workflow_foundation_wall_air_sealing_and_insulation.mdx, src/templates/ira_doe_workflow_limited_assessment.mdx, src/templates/ira_doe_workflow_slap_foundation_exterior_sealing_and_insulation.mdx, src/templates/ira_doe_workflow_wall_air_sealing_and_insulation_dry_fill.mdx, src/templates/labelValueExamples/DateLabelValues.mdx, src/templates/labelValueExamples/LabelValueExamplesStyles.css, src/templates/labelValueExamples/NumberLabelValues.mdx, src/templates/labelValueExamples/OtherExamples.mdx, src/templates/labelValueExamples/TextLabelValues.mdx, src/templates/playground.mdx, src/templates/reusable/project_info_report.mdx, src/utilities/cloning_utils.ts, src/utilities/string_to_number_utils.ts, yarn.lock
- Added functionality as described in https://github.com/pnnl/Quality-Install-Tool/issues/254.
- Replaced instances of `<strong>Label: </strong><p>Value</p>` with `<LabelValue/>`
- Added a Playground tab with examples.
=> 254 Label Value

public/index.html
=> DAP script added
